language: cpp

sudo: required
dist: trusty

matrix:
  include:

    ###########################################################################
    # GCC on Linux.
    #

    #
    # GCC 7 Release.
    #
    - os: linux
      env:
        - JOB="GCC 7 Release"
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - BUILD_TYPE=Release
      addons: &gcc7
        apt:
          packages:
            - gcc-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
      script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir -p build && cd build
        - |
          conan install .. --build missing \
            -s build_type=${BUILD_TYPE} \
        - cmake .. -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}
        - cmake --build . --config ${BUILD_TYPE} -- -j2

    #
    # GCC 7 Release + codecov + coveralls.
    #
    - os: linux
      env:
        - JOB="GCC 7 Release + Codecov and Coveralls"
        - CC_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - BUILD_TYPE=Release
        - ENABLE_TESTING=TRUE
        - ENABLE_COVERAGE=TRUE
      addons: *gcc7
      before_install:
        - pip install --user cpp-coveralls
      script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir -p build && cd build
        - |
          conan install .. --build \
            -s build_type=${BUILD_TYPE} \
            -s compiler.libcxx=libstdc++11
        - |
          cmake .. \
            -DCMAKE_BUILD_TYPE:STRING=${BUILD_MODE} \
            -DENABLE_TESTING:BOOL=${ENABLE_TESTING} \
            -DENABLE_COVERAGE:BOOL=${ENABLE_COVERAGE}
        - cmake --build . --config ${BUILD_TYPE} -- -j2
      after_success:
        - ctest --extra-verbose --parallel 2
        - |
          lcov --directory . --capture --output-file coverage.info # capture coverage info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
          # Codecov - upload the report.
          bash <(curl -s https://codecov.io/bash)
          # Coveralls - upload the report.
          cd ..
          coveralls --build-root build --gcov-options '\-lp' \
            -e build/external \
            -e build/catch \
            -e cmake \
            -E ".*CMakeFiles.*"

install:
  # Set up the environment.
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      # Set the ${CC} variable properly.
      export CC=${CC_COMPILER}
    fi
  # Set the ${CXX} variable properly.
  - export CXX=${CXX_COMPILER}

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/.
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  # Install a recent CMake and Conan.
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      CMAKE_VERSION=3.10.0
      CMAKE_ARCH=cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/${CMAKE_ARCH}"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      sudo pip install conan
    fi